name = "cf-chat"
main = "src/router.ts"

compatibility_date = "2024-12-31"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "ChatRoom" },
  { name = "DEBOUNCE", class_name = "RateLimiter" },
  { name = "GAMES", class_name = "GameSession" },
]

[[rules]]
type = "Data"
globs = ["**/*.html", "**/*.pug"]
fallthrough = false

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "GameSession", "RateLimter"]