name = "cf-chat"
main = "src/chat.mjs"

compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "ChatRoom" },
  { name = "DEBOUNCE", class_name = "RateLimiter" },
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom", "RateLimter"]