name = "cf-chat"
main = "src/chat.mts"

compatibility_date = "2024-12-24"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "ROOMS", class_name = "ChatRoom" },
]

[[migrations]]
tag = "v1"
new_classes = ["ChatRoom"]